implement fourth.SaveAvatar
aprzn123/TheThirdCan pull request #47
Opened 2023-06-26 20:56 UTC by HumanoidSandvichDispenser

fetch request in stealAvatarButton.js is moved to a fourth method fourth.SaveAvatar to avoid making arbitrary fetch requests https://github.com/aprzn123/TheThirdCan/issues/22#issuecomment-1457212864 and also avoid rewriting code for #38

2023-06-29 06:34 UTC, HumanoidSandvichDispenser commented on src/injected/stealAvatarButton.js
> +    // to API functions
in retrospect i think this isn't worth the hassle

2023-06-29 06:35 UTC, HumanoidSandvichDispenser commented on src/injected/stealAvatarButton.js
> +    // to API functions
unless there is some way that the extension is going to track the user's id across pages

2023-07-02 15:51 UTC, aprzn123 requested changes
can you document the new function in `docs/third_fourth.md`? we don't have doc gen from the comments atm

2023-07-03 00:04 UTC, thekifake commented
> we don't have doc gen from the comments atm

Hopefully we can do something about that eventually. I'll see if I can maybe figure things out.

2023-07-03 13:03 UTC, aprzn123 approved these changes
i feel like i've been avoiding merging this but tbh i really don't know why so let's just go for it lol

2023-07-03 13:03 UTC, merged