Return of Binoculars
aprzn123/TheThirdCan pull request #48
Opened 2023-06-26 21:25 UTC by thekifake

I believe this is actually quite a bit faster than the original method. Uses API calls now rather than just scraping information from the forum homepage.

![](https://i.ibb.co/S3gvKcd/vivaldi9335-1687814577.gif)

2023-06-28 22:47 UTC, aprzn123 requested changes

2023-06-28 22:47 UTC, aprzn123 commented on src/injected/default_settings.json
> +  "useBinoculars": true
I would suggest useBinoculars as false by default so it doesn't clutter up the page for users who don't care about it

2023-06-28 22:47 UTC, aprzn123 commented on src/injected/binoculars.js
> +        if (id == users.length - 2) str += " and"; //...why? why does === not work and only == does? what the fuck?
To your comment, I'm pretty sure I saw this issue recently and it's kinda fucked up: the for-in loop makes `id` a string

2023-06-29 21:15 UTC, thekifake commented on src/injected/binoculars.js
> +        if (id == users.length - 2) str += " and"; //...why? why does === not work and only == does? what the fuck?
...What in the world? Why?

2023-06-29 22:53 UTC, HumanoidSandvichDispenser commented on src/injected/binoculars.js
> +        if (id == users.length - 2) str += " and"; //...why? why does === not work and only == does? what the fuck?
for-in loops iterate through object properties and it's not meant to be used with arrays

2023-06-29 23:12 UTC, aprzn123 commented on src/injected/binoculars.js
> +        if (id == users.length - 2) str += " and"; //...why? why does === not work and only == does? what the fuck?
> ...What in the world? Why?

Javascript. Need I say more?

2023-07-02 15:48 UTC, aprzn123 approved these changes

2023-07-02 15:48 UTC, merged